export const farmFields = [
  'id',
  'name',
  'userId',
  'location',
  'latitude',
  'longitude',
  'pictures',
  'createdAt',
  'email',
  'phone',
  'description',
  'farmSlug',
  // 'bookings',
  // 'createdEvents',
  'activities',
  'user',
  // 'favorites',
  // 'jobs',
  // 'products',
];

export const farmTransformer = (farm) => {
  return {
    id: farm.id,
    name: farm.name,
    userId: farm.userId,
    location: farm.location,
    latitude: farm.latitude,
    longitude: farm.longitude,
    pictures: farm.pictures,
    createdAt: farm.createdAt,
    email: farm.email,
    phone: farm.phone,
    description: farm.description,
    farmSlug: farm.farmSlug,
    bookings: farm.bookings,
    createdEvents: farm.createdEvents,
    activities: farm.activities,
    user: farm.user,
    favorites: farm.favorites,
    jobs: farm.jobs,
    products: farm.products,
  };
};
