export const userFields = [
  'id',
  'email',
  'name',
  'image',
  'picture',
  'profileImage',
  'createdAt',
  'updatedAt',
  'phone',
  'username',
  // 'farmSlug',
  'role',
  'type',
  'credits',
  'agreedTerms',
  'locale',
  'description',
  'workerExperience',
  'specialties',
  'schedule',
  'languages',
];

export const userTransformer = (user) => {
  return {
    id: user.id,
    name: user.name,
    email: user.email,
    username: user.username,
    phone: user.phone,
    profileImage: user.profileImage,
    picture: user.picture,
    image: user.image,
    handle: '@' + user.username,
    type: user.type,
    credits: user.credits,
    farmSlug: user.farmSlug,
    farmName: user.farmName,
    agreedTerms: user.agreedTerms,
    locale: user.locale,
    description: user.description,
    workerExperience: user.workerExperience,
    specialties: user.specialties,
    schedule: user.schedule,
    languages: user.languages,
  };
};
