/** @type {import('tailwindcss').Config} */
module.exports = {
  presets: [require('tailwindcss-preset-email')],
  theme: {
    extend: {
      colors: {
        transparent: 'transparent',
        current: 'currentColor',
        white: '#ffffff',
        primary: '#4B6700',
        secondary: '#5A6148',
        accent: '#CBF080',
        'dark-page': '#13140F',
        dark: '#1d1d1d',
        positive: '#B0D367',
        negative: '#BA1A1A',
        info: '#396660',
        warning: '#FFCB00',
        lime: '#cbf080',
        'dark-lime': '#b0d367',
        pistachio: '#dee6c5',
        olive: '#c6c8b9',
        'dark-olive': '#76786b',
        'black-olive': '#45483c',
        'light-cocomilk': '#fbf9f1',
        'darker-cocomilk': '#f2f1e9',
        grey: '#e4e4e4',
        'dark-primary': '#374e00',
        'dark-green': '#171e09',
        'soft-dark-green': '#1b1c17',
        'dark-white-sand': '#dbdad3',
        'white-sand': '#eae8e0',
        sand: '#e4e3db',
        'light-sand': '#efeee6',
        'blood-red': '#93000a',
        red: '#ff5449',
      },
    },
  },
};
